### ISSUE TITLE
Change Builder type parameters to support trait objects on builder methods

### ISSUE THREAD

**Issue by MinisculeGirraffe** [koenichiwa/const_typed_builder#62]
Howdy. 

I feel like it should be possible to change the function signature on the field methods to use trait objects. These are monomorphic at compile time and wouldn't have any runtime penalty compared to writing the code by hand.

Examples:

[Into](https://doc.rust-lang.org/std/convert/trait.Into.html) for owned valued:
```Rust
pub fn bar(self, baz: String) -> ReturnType
```

```Rust
pub fn bar(self, baz: impl Into<String>) -> ReturnType
```
[AsRef](https://doc.rust-lang.org/std/convert/trait.AsRef.html) for References

```Rust
pub fn bar(self, baz: &str) -> ReturnType
```
```Rust
pub fn bar(self, baz: impl AsRef<str>) -> ReturnType
```
[AsMut](https://doc.rust-lang.org/std/convert/trait.AsMut.html) for mutable references

```Rust
pub fn bar(self, baz: &mut str) -> ReturnType
```
```Rust
pub fn bar(self, baz: impl AsMut<str>) -> ReturnType
```

This would allow any type that could be represented as the type the builder needs to be used as a satisfactory parameter.

Example:

Explicit Type Parameter
```Rust
let foo = Foo::builder()
    .bar("Hello".to_string())
    .baz("world!".to_string())
    .qux("Hello".to_string())
    .quz("world!".to_string())
    .build();
```
With `impl Trait` Type Parameter
```Rust
let foo = Foo::builder()
    .bar("Hello")
    .baz("world!")
    .qux("Hello")
    .quz("world!")
    .build();
```

This is often more flexible and less verbose as a public API since you don't *have* to provide a string, just something that could be represented as a string.

**Comment by koenichiwa** [comment]
That's a very good point! 

How do you think this should be done by the user?  By adding an attribute like `#[builder(into)]` to the struct field? Or do you have a different idea?

Example of usage:
```rust
#[derive(Builder)]
struct Foo<'a> {
    #[builder(into)]
    bar: PathBuf,
    #[builder(asref)]
    baz: &'a str,
}

let my_str = String::from("Hello world!");
let foo = Foo::builder()
    .bar("/tmp")
    .baz(&my_str)
    .build();
```

I'm still a bit curious how it would work with optional fields, but I guess I'll have to explore that a bit more.

**Comment by MinisculeGirraffe** [comment]
To me at least this makes sense as a default behavior since it doesn't change anything from the callers perspective. A `String` will always implement `Into<String>`. Same with the other traits.  No existing functionality is lost, but flexibility is gained.

A down side to this would be that type signatures might become less clear because of the trait objects. To me that's worth it, but i'm biased. 

Options work basically the same way for all of the traits, it just changes how the trait object is resolved.

```rust
pub fn bar(self, baz: Option<impl Into<String>>) -> ReturnType
```
To resolve the trait object it would just require doing
 ```rust
 baz.map(|i| i.into())
```
Compared to 
 ```rust
 baz.into()
```

What's cool is that all of these ways of calling bar would be considered valid with `Option<impl Into<String>>`.

```rust
#[derive(Builder)]
struct Foo<'a> {
    #[builder(into)]
    bar:Option<String>,
}

let foo = Foo::builder()
    .bar("Foo") //&str
    .bar(Some("Foo")) // Option<&str>
    .bar("Foo".to_string()) // String
    .bar(Some("Foo".to_string())) // Option<String>
    .build()
```
Everyone of those types can be represented as an `Option<String>` with Into, so it doesn't matter which one we provide to the builder function.

**Comment by koenichiwa** [comment]
> To me at least this makes sense as a default behavior since it doesn't change anything from the callers perspective.

True, but the macro can't check if the underlying type implements a certain trait like `Into`. If the user has defined a struct himself, instead of using `std::String` then theres no way of knowing that when the macro is "unpacked". It basically would force the user to implement either `From` or` Into` for that struct, before using this crate. I don't think that would be the right course to take.

On the other hand, to use `into` as default you could also give the user the option to define it at struct level like:

```rust
#[derive(Builder)]
#[builder(into)]
struct Foo<'a> {
    bar:Option<String>,
}
```

Where every field is treated as if it implements `Into` until specified otherwise. 

But then I would need a good attribute name for the user to get it back to its current default behaviour... Currently we have `into`, `asref`, and `asmut`. But how would we call it if we want none of those?

Anyways, would defining it at struct level work sufficiently for you?

**Comment by MinisculeGirraffe** [comment]
> the macro can't check if the underlying type implements a certain trait like Into. If the user has defined a struct himself, instead of using std::String

This actually isn't a problem, per the Rust docs.

> [Into](https://doc.rust-lang.org/std/convert/trait.Into.html) is reflexive, which means that Into\<T\> for T is implemented

Basically in the stdlib they have this trait implementation written, which applies to every single type in the language.

```rust
impl Into<T> for T {
    fn into(self) -> T {
        self
    }
}
```

Every single type in Rust will always have Into implemented for itself by default.  So using the Into trait as a parameter will always accept at least the original type, and the conversion is basically a no-op.

For example, the following code still works even though I didn't actually implement `Into` for `IntoTest`.

```rust
struct IntoTest();

fn test_into(val: impl Into<IntoTest>) {
    let val = val.into();
}

fn main() {
    let test = IntoTest();
    test_into(test)
}
```

**Comment by MinisculeGirraffe** [comment]
An important point though would be that AsRef and AsMut are not reflexive, so those would need an annotation on the field likely.

**Comment by koenichiwa** [comment]
Alright, sounds good, I'll work on it. I'm currently doing a major refactoring step in preparation to supporting enums. After I'm done refactoring I can work on this.

I'm still not convinced on doing `into` as default, but I'll look into it further. Adding an annotation  on struct level, so the user can to opt in using `into`, sounds safer to me for now. I need to see what other people's opinions are on this matter

**Comment by koenichiwa** [comment]
@MinisculeGirraffe I'm having some trouble implementing `AsRef`, I hoped you could help me out. `Into` was very easy, and I haven't started with `AsMut` yet. 

The problem lies within the setter. I'm basically having issues with the lifetime.

For now, if I have this struct
```rust
#[derive(Builder)]
pub struct Foo<'a> {
   #[builder(setter = asref)]
    bar: &'a str,
}
```

It will desugar into:
```rust
pub struct Foo<'a> {
    bar: &'a str,
}

pub trait Builder<'a> {
    type BuilderImpl;
    fn builder() -> Self::BuilderImpl;
}

impl<'a> Builder<'a> for Foo<'a> {
    type BuilderImpl = FooBuilder<'a, false>;
    #[doc = "Creates an instance of [`FooBuilder`]"]
    fn builder() -> Self::BuilderImpl {
        Self::BuilderImpl::new()
    }
}
#[doc = "Builder for [`Foo`] derived using the `const_typed_builder` crate"]
pub struct FooBuilder<'a, const __BUILDER_CONST_0: bool> {
    __foo_data: FooData<'a>,
}
impl<'a> FooBuilder<'a, false> {
    #[doc = "Creates a new [`FooBuilder`] without any fields initialized"]
    pub fn new() -> FooBuilder<'a, false> {
        Self::default()
    }
}
impl<'a> Default for FooBuilder<'a, false> {
    #[doc = "Creates a new [`FooBuilder`] without any fields initialized"]
    fn default() -> Self {
        FooBuilder {
            __foo_data: FooData::default(),
        }
    }
}
impl<'a> FooBuilder<'a, false> {
    #[doc = "\nSetter for the [`Foo::bar`] field.\n\n# Arguments\n\n- `bar`: field to be set\n\n# Returns\n\n`FooBuilder` with `bar` initialized"]
    pub fn bar(self, bar: impl AsRef<str> + 'a) -> FooBuilder<'a, true> {
        let mut __foo_data = self.__foo_data;
        __foo_data.bar = Some(bar.as_ref());
        FooBuilder { __foo_data } // this line does not work
    }
}
impl<'a> FooBuilder<'a, true> {
    #[doc = "Build an instance of [`Foo`], consuming the [`FooBuilder`]"]
    pub fn build(self) -> Foo<'a> {
        self.__foo_data.into()
    }
}
#[doc(hidden)]
pub struct FooData<'a> {
    pub bar: Option<&'a str>,
}
impl<'a> From<FooData<'a>> for Foo<'a> {
    #[doc(hidden)]
    fn from(data: FooData<'a>) -> Foo<'a> {
        Foo {
            bar: data.bar.unwrap(),
        }
    }
}
impl<'a> Default for FooData<'a> {
    #[doc(hidden)]
    fn default() -> Self {
        FooData { bar: None }
    }
}
```
But that gives me the following error:
```
error[E0515]: cannot return value referencing function parameter `bar`
  --> src/main.rs:40:9
   |
39 |         __foo_data.bar = Some(bar.as_ref());
   |                               --- `bar` is borrowed here
40 |         FooBuilder { __foo_data } // this line does not work
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^ returns a value referencing data owned by the current function
```

I also thought about using `std::mem::transmute`, even though I'm hesitant to use `unsafe`
```rust
impl<'a> FooBuilder<'a, false> {
    pub fn bar(mut self, bar: impl AsRef<str> + 'a) -> FooBuilder<'a, true> {
        self.__foo_data.bar = Some(bar.as_ref());
        unsafe { std::mem::transmute(self) }
    }
}
```

```
error[E0597]: `bar` does not live long enough
  --> src/main.rs:38:36
   |
35 | impl<'a> FooBuilder<'a, false> {
   |      -- lifetime `'a` defined here
36 |     #[doc = "\nSetter for the [`Foo::bar`] field.\n\n# Arguments\n\n- `bar...
37 |     pub fn bar(mut self, bar: impl AsRef<str> + 'a) -> FooBuilder<'a, true> {
   |                          --- binding `bar` declared here
38 |         self.__foo_data.bar = Some(bar.as_ref());
   |         ---------------------------^^^----------
   |         |                          |
   |         |                          borrowed value does not live long enough
   |         assignment requires that `bar` is borrowed for `'a`
39 |         unsafe { std::mem::transmute(self) }
40 |     }
   |     - `bar` dropped here while still borrowed
```

**Comment by koenichiwa** [comment]
P.S. I was already hesitant using it, but`std::mem::transmute` seems not to be an option at all, because it does not play nice if `Foo` has generics of its own.

**Comment by koenichiwa** [comment]
Nevermind, I'm tired. Got it to work with
```rust
pub fn bar(mut self, bar: &'a  impl AsRef<str>) -> FooBuilder<'a, true> {
        self.__foo_data.bar = Some(bar.as_ref());
        FooBuilder { __foo_data: self.__foo_data }
    }
```

**Comment by koenichiwa** [comment]
I think I made it work. Could you please check if this is kind of what you expected? You can find the tested use cases [here](https://github.com/koenichiwa/const_typed_builder/blob/9ddf18a2cdbb62dc7b63444c1689d655e9796e0f/const_typed_builder_test/src/lib.rs#L702-L836C6)

## Usage
I decided on the following:
1. You can choose one of the following setter "kinds" at field level
  1. standard (what the current default is)
  2. propagate (propagating to another builder made with the same derive)
  3. into (field `T` is set with `impl Into<T>`, field `Option<T>` is set with `Option<impl Into<String>>`)
  4. asref (field `&'a str`-> `&'a impl AsRef<str>`, `Option<&'a str>` => `Option<&'a impl AsRef<str>>`)
  5. asmut (field `&'a mut str`-> `&'a mut impl AsMut<str>`, `Option<&'a mut str>` => `Option<&'a mut impl AsRef<str>>`)
2. into can also be defined at struct level, upon which all fields are assumed to be of "kind" into, unless defined otherwise

## Changes from what we decided earlier
In your examples you had something like
```rust
pub fn bar(self, baz: impl AsRef<str>) -> ReturnType
```
But if I generated this code snippet:
```rust
impl<'a> FooBuilder<'a, false> {
    pub fn bar(mut self, bar: impl AsRef<str>) -> FooBuilder<'a, true> {
        self.__foo_data.bar = Some(bar.as_ref());
        FooBuilder { __foo_data: self.__foo_data }
    }
}
```
The compiler gave me this error:
```
the parameter type `impl AsRef<str>` may not live long enough
...so that the type `impl AsRef<str>` will meet its required lifetime bounds
```

Thats why I eventually settled on the references like `&'a impl AsRef<str>`. I didn't need to do this with `Into`
